## caskroom/cask
tap 'caskroom/cask'

## homebrew/binary
tap 'homebrew/binary'

## homebrew/dupes
tap 'homebrew/dupes'

tap 'caskroom/fonts'

tap 'homebrew/fuse'
cask 'osxfuse'
brew 'homebrew/fuse/ntfs-3g'

brew 'autojump'
brew 'archey'
brew 'axel'
brew 'bash'
brew 'boot2docker'
brew 'curl'
brew 'docker'
brew 'docker-compose'
brew 'docker-machine'
brew 'emacs'
brew 'geoip'
brew 'git'
brew 'git-flow'
brew 'go'
brew 'heroku'
brew 'heroku-toolbelt'
brew 'htop'
brew 'httpie'
brew 'hub'
brew 'irssi'
brew 'imagemagick'
brew 'lynx'
brew 'mc'
brew 'mysql', restart_service: true
brew 'ncdu'
brew 'nmap'

brew 'openssl'
brew 'peco'
brew 'postgres', restart_service: true
brew 'pyenv'
brew 'python'
brew 'python3'
brew 'qt5'
brew 'redis', restart_service: true
brew 'siege'
brew 'speedtest-cli'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'terminal-notifier'
brew 'thefuck'
brew 'the_silver_searcher'
brew 'tmux'
brew 'trash'
brew 'tree'
brew 'v8'
brew 'vim', args: ['override-system-vi','override-system-vim']
brew 'watch'
brew 'wget'
brew 'xz'
brew 'zsh'


cask_args appdir: '~/Applications'
cask 'air-video-server-hd'
##, args: { appdir: '/Applications' }
# cask 'abricotine' Markdown editor
cask 'appcleaner'
cask 'atom'
cask 'caffeine'
cask 'chromium'
cask 'dash'
cask 'dropbox'
cask 'espresso'
cask 'filezilla'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'java' unless system '/usr/libexec/java_home --failfast'
cask 'macdown'
# cask 'mou' Markdown editor
cask 'no-ip-duc'
cask 'ngrok'
cask 'qbittorrent'
cask 'qt-creator'
cask 'seil'
cask 'sequel-pro'
cask 'skype'
cask 'steam'
cask 'sublime-text'
cask 'slack'
cask 'teamviewer'
cask 'toggldesktop'
cask 'transmission'
cask 'tunnelbear'
# cask 'tower'
cask 'vagrant'
cask 'viber'
cask 'virtualbox'
cask 'vlc'
cask 'vox-preferences-pane'
cask 'vox'

cask 'font-hack'
cask 'font-source-code-pro'

cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'
cask 'betterzipql'
cask 'qlimagesize'
cask 'webpquicklook'
cask 'suspicious-package'
cask 'quicklookase'
cask 'qlvideo'
